name: Test `@saulhardman/refresh-instagram-access-token` GitHub Action

jobs:
  test:
    timeout-minutes: 5

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Refresh Instagram Access Token
        uses: ./
        with:
          access_token: ${{ secrets.INSTAGRAM_ACCESS_TOKEN }}
